name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        python-version: ['3.8', '3.9']
      fail-fast: false
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports: 
          - 4444:4444
        options: --shm-size="2g"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup-chromedriver
      uses: nanasess/setup-chromedriver@v1.0.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pathlib
        pip install pytest
        pip install selenium==4.1.2
        
        
    - name: Test with pytest
      run: python -m pytest